const $=id=>document.getElementById(id);
const KEY="robotintelligence.agent.v1";
const STATES=["UNDERSTAND","PLAN","SEARCH","VERIFY","DECIDE","EXECUTE","TEST","COMMIT","ROLLBACK","DONE"];
let stopped=false;
let state=load();
function base(){return{version:1,run:{status:"IDLE",goal:"",asset:"",query:"",plan:[],evidence:[],candidates:[],decisions:[],errors:[],providers:0,retries:0,checkpoint:null},memory:{runs:[],lastDecision:""},log:[]}}
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));return x&&x.version===1?x:base()}catch{return base()}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));render()}
function esc(v){return String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")}
function write(kind,msg){state.log.unshift({t:Date.now(),kind,msg});state.log=state.log.slice(0,200);save()}
function decision(type,msg){state.run.decisions.unshift({t:Date.now(),type,msg});state.memory.lastDecision=msg;write("DECISION",msg)}
const tools={
 ok:(data,meta={})=>({ok:true,data,error:null,meta}),
 fail:(error,meta={})=>({ok:false,data:null,error,meta}),
 async github(q){try{const r=await fetch("https://api.github.com/search/repositories?q="+encodeURIComponent(q)+"&sort=updated&order=desc&per_page=10",{headers:{Accept:"application/json"}});if(!r.ok)return this.fail(r.status+" "+r.statusText,{tool:"github"});const d=await r.json();return this.ok(d.items||[],{tool:"github",count:(d.items||[]).length})}catch(e){return this.fail(e.message,{tool:"github"})}},
 async hn(q){try{const r=await fetch("https://hn.algolia.com/api/v1/search?query="+encodeURIComponent(q)+"&tags=story&hitsPerPage=10");if(!r.ok)return this.fail(r.status+" "+r.statusText,{tool:"hackernews"});const d=await r.json();return this.ok(d.hits||[],{tool:"hackernews",count:(d.hits||[]).length})}catch(e){return this.fail(e.message,{tool:"hackernews"})}},
 checkpoint(){state.run.checkpoint=JSON.parse(JSON.stringify(state.run));write("CHECKPOINT","Checkpoint saved before external search.");return this.ok(true,{tool:"checkpoint"})},
 restore(){if(!state.run.checkpoint)return this.fail("No checkpoint");state.run=JSON.parse(JSON.stringify(state.run.checkpoint));write("ROLLBACK","Restored last checkpoint.");return this.ok(true,{tool:"rollback"})},
 validate(){const r=state.run;const errors=[];if(r.providers===0)errors.push("No source responded");if(!r.evidence.length)errors.push("No evidence");if(r.evidence.some(x=>x.entity&&/^(ai|robot|robotics|learning|project|demo)$/i.test(x.entity)))errors.push("Noise entity detected");if(r.candidates.some(x=>!x.liveEvidence))errors.push("Candidate without evidence");return errors.length?this.fail(errors.join("; "),{tool:"validator",errors}):this.ok({pass:true},{tool:"validator"})}
};
function makePlan(){return STATES.map((name,i)=>({name,status:i===0?"running":"pending",detail:{UNDERSTAND:"Parse goal and asset.",PLAN:"Bound search and validation steps.",SEARCH:"Query public evidence sources.",VERIFY:"Normalize evidence and resolve entities.",DECIDE:"Select coherent commercial candidates.",EXECUTE:"Prepare local action state only.",TEST:"Validate evidence quality and coherence.",COMMIT:"Persist verified run to memory.",ROLLBACK:"Restore checkpoint after failed validation.",DONE:"Finish with auditable result."}[name]}))}
function normalize(gh,hn){const out=[];for(const x of gh)out.push({source:"GitHub",title:x.full_name,description:x.description||"",url:x.html_url,date:x.updated_at,entity:x.owner?.type==="Organization"?x.owner.login:""});for(const x of hn)out.push({source:"Hacker News",title:x.title||"",description:x.title||"",url:x.url||("https://news.ycombinator.com/item?id="+x.objectID),date:x.created_at,entity:""});return out}
function candidates(){const g={};for(const e of state.run.evidence){const t=(e.title+" "+e.description+" "+e.entity).toLowerCase();const rel=["robot","robotics","humanoid","embodied","physical ai","robot learning","manipulation","autonomy","intelligence"].filter(k=>t.includes(k)).length;if(!e.entity||rel<1)continue;const k=e.entity.toLowerCase();g[k]??={name:e.entity,signals:[],rel:0};g[k].signals.push(e);g[k].rel=Math.max(g[k].rel,rel)}return Object.values(g).map(x=>({name:x.name,liveEvidence:x.signals.length,relevance:x.rel,score:Math.min(100,35+x.rel*7+x.signals.length*6)})).sort((a,b)=>b.score-a.score)}
function setPhase(p){state.run.status=p;const row=state.run.plan.find(x=>x.name===p);if(row)row.status="running";save();write("STATE",p)}
async function run(){stopped=false;state.run={...base().run,goal:$("goal").value.trim(),asset:$("asset").value.trim(),query:$("query").value.trim(),plan:makePlan()};if(!state.run.goal||!state.run.asset){write("ERROR","Goal and asset are required.");return}for(const p of STATES.slice(0,8)){if(stopped){write("STOP","Stopped by operator.");return}setPhase(p);if(p==="UNDERSTAND")decision("UNDERSTAND","Goal accepted: "+state.run.goal);if(p==="PLAN")decision("PLAN","Using GitHub + Hacker News, normalization, validation and rollback.");if(p==="SEARCH"){tools.checkpoint();const q=(state.run.query||state.run.asset)+" robotics AI";const [gh,hn]=await Promise.all([tools.github(q),tools.hn(q)]);if(gh.ok){state.run.providers++;state.run.evidence.push(...normalize(gh.data,[]))}else state.run.errors.push("GitHub: "+gh.error);if(hn.ok){state.run.providers++;state.run.evidence.push(...normalize([],hn.data))}else state.run.errors.push("HN: "+hn.error);decision("SEARCH","Collected "+state.run.evidence.length+" public evidence items.")}if(p==="VERIFY"){state.run.candidates=candidates();decision("VERIFY","Resolved "+state.run.candidates.length+" evidence-backed entities.")}if(p==="DECIDE")decision("DECIDE",state.run.candidates.length?"Proceed with local intelligence result.":"No candidate passed the evidence gate.");if(p==="EXECUTE")decision("EXECUTE","External side effects remain disabled; only local state is changed.");if(p==="TEST"){const v=tools.validate();if(!v.ok){state.run.errors.push(v.error);decision("TEST","Validation failed; entering rollback/retry.");state.run.retries++;tools.restore();if(state.run.retries<2){state.run.query=(state.run.query+" commercial company").trim();return run()}setPhase("ROLLBACK");return}decision("TEST","Validation passed.")}if(p==="COMMIT"){state.memory.runs.unshift({at:Date.now(),goal:state.run.goal,asset:state.run.asset,evidence:state.run.evidence.length,candidates:state.run.candidates.length});state.memory.runs=state.memory.runs.slice(0,20);decision("COMMIT","Run persisted to local agent memory.")}const row=state.run.plan.find(x=>x.name===p);if(row)row.status="done";save();await new Promise(r=>setTimeout(r,100))}setPhase("DONE")}
function render(){const r=state.run;$("stateName").textContent=r.status;$("health").textContent=r.errors.length?"ATTENTION":"READY";$("evidenceCount").textContent=r.evidence.length+" evidence";$("stateGrid").innerHTML=STATES.slice(0,10).map(x=>'<div class="state-card '+(x===r.status?"active":"")+'"><b>'+x+'</b><small>'+((r.plan.find(y=>y.name===x)||{}).status||"pending")+'</small></div>').join("");$("plan").innerHTML=r.plan.map(x=>'<div class="plan-card '+x.status+'"><div class="step">'+x.name+'</div><h3>'+x.status.toUpperCase()+'</h3><p>'+x.detail+'</p></div>').join("");$("evidence").innerHTML=r.evidence.slice(0,40).map(x=>'<article class="evidence-card"><div class="evidence-meta">'+x.source+'</div><h3>'+esc(x.title)+'</h3><p>'+esc(x.description)+'</p><p><b>Entity:</b> '+esc(x.entity||"unresolved")+'</p><a href="'+esc(x.url)+'" target="_blank" rel="noopener">OPEN SOURCE ↗</a></article>').join("")||'<div class="log-item">No evidence yet.</div>';$("decisions").innerHTML=r.decisions.map(x=>'<div class="decision"><span>'+new Date(x.t).toLocaleTimeString()+" · "+esc(x.type)+'</span><strong>'+esc(x.msg)+'</strong></div>').join("")||'<div class="log-item">No decisions yet.</div>';$("log").innerHTML=state.log.map(x=>'<div class="log-item"><time>'+new Date(x.t).toLocaleTimeString()+'</time><b>'+esc(x.kind)+'</b> '+esc(x.msg)+'</div>').join("")||'<div class="log-item">No log entries.</div>'}
function init(){$("run").onclick=()=>run().catch(e=>write("ERROR",e.message));$("stop").onclick=()=>{stopped=true;write("STOP","Stop requested.")};$("retry").onclick=()=>run();$("continue").onclick=()=>run();$("reset").onclick=()=>{state=base();save()};$("clearLog").onclick=()=>{state.log=[];save()};render()}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();