const BASE_URL="https://api.apollo.io/api/v1";
function enabled(kind="search"){return kind==="enrichment"?String(process.env.APOLLO_ENABLE_ENRICHMENT||"").toLowerCase()==="true":String(process.env.APOLLO_ENABLE_FREE_SEARCH||"").toLowerCase()==="true";}
function apiKey(){return process.env.APOLLO_API_KEY||"";}
function ensureConfigured(kind="search"){if(!enabled(kind)||!apiKey())throw new Error("apollo_disabled");}
async function request(path,body,kind="search"){ensureConfigured(kind);const response=await fetch(BASE_URL+path,{method:"POST",headers:{"accept":"application/json","content-type":"application/json","x-api-key":apiKey()},body:JSON.stringify(body)});if(!response.ok){const detail=await response.text().catch(()=> "");throw new Error("apollo_http_"+response.status+(detail?":"+detail.slice(0,180):""));}return response.json();}
function domainTerms(domain){const sld=String(domain||"").split(".")[0].toLowerCase();const dictionary=["robot","intelligence","humanoid","behavior","planning","context","embodiment","robotics","agents","physical","manipulation","stack","world","publication","ai","ui"];return dictionary.filter(k=>sld.includes(k));}
const buyerTitles=["CEO","Founder","Chief Executive Officer","Chief Technology Officer","CTO","VP","Head of AI","Head of Robotics","Robotics"];
function normalizePerson(p){return {id:p.id||null,name:[p.first_name,p.last_name].filter(Boolean).join(" ")||p.name||"Unknown",title:p.title||null,organization_id:p.organization_id||p.organization?.id||null,organization_name:p.organization_name||p.organization?.name||null,organization_domain:p.organization?.primary_domain||p.organization?.domain||null,organization_industry:p.organization?.industry||null,organization_description:p.organization?.short_description||p.organization?.description||null,organization_employees:p.organization?.estimated_num_employees||null,organization_funding:p.organization?.latest_funding_amount||null,linkedin_url:p.linkedin_url||null,source:"Apollo People API Search"};}
function normalizeOrganizationFromPerson(p){const o=p.organization||{};return {id:p.organization_id||o.id||null,name:p.organization_name||o.name||null,website_url:o.website_url||o.primary_domain||o.domain||null,primary_domain:o.primary_domain||o.domain||null,industry:o.industry||null,description:o.short_description||o.description||null,employees:o.estimated_num_employees||null,funding:o.latest_funding_amount||null,latest_funding_date:o.latest_funding_date||null,fit:0,matched_terms:[],source:"Apollo People API Search"};}
function scoreOrganization(org,terms){const hay=[org.name,org.description,org.industry,org.primary_domain].filter(Boolean).join(" ").toLowerCase();const hits=terms.filter(t=>hay.includes(t));return {score:Math.min(100,Math.round(45+hits.length*12+(Number(org.funding||0)>0?8:0)+(Number(org.employees||0)>=50?8:0))),hits};}
async function findCompanies(domain,{perPage=10}={}){const terms=domainTerms(domain);const data=await request("/mixed_people/api_search",{page:1,per_page:Math.min(25,Math.max(1,perPage)),q_keywords:terms.length?terms.join(" "):"robotics artificial intelligence",person_seniorities:["founder","c_suite","vp","head","director"],person_titles:buyerTitles,include_similar_titles:true});const byId=new Map();(data.people||[]).map(normalizeOrganizationFromPerson).forEach(org=>{if(org.id&&org.name&&!byId.has(org.id))byId.set(org.id,org);});const organizations=[...byId.values()].map(org=>{const fit=scoreOrganization(org,terms);return {...org,fit:fit.score,matched_terms:fit.hits};}).sort((a,b)=>b.fit-a.fit);return {connector:"apollo",status:"live",domain,terms,organizations,meta:{total:organizations.length,credits:"0 credits for People API Search",discovery:"optional"} }; }
async function findDecisionMakers(organizationIds,{perPage=5}={}){const ids=(organizationIds||[]).filter(Boolean);if(!ids.length)return {connector:"apollo_people",status:"live",people:[],meta:{credits:"0 credits"}};const data=await request("/mixed_people/api_search",{page:1,per_page:Math.min(25,Math.max(1,perPage)),organization_ids:ids.slice(0,10),person_seniorities:["founder","c_suite","vp","head","director"],person_titles:buyerTitles,include_similar_titles:true});return {connector:"apollo_people",status:"live",people:(data.people||[]).map(normalizePerson),meta:{credits:"0 credits for People API Search"}};}
async function enrichDecisionMakers(domain,{perPage=5,maxPeople=5}={}){if(!enabled("enrichment"))throw new Error("apollo_enrichment_disabled");const companies=await findCompanies(domain,{perPage:Math.min(10,perPage)});const ids=companies.organizations.map(x=>x.id).filter(Boolean);const people=await findDecisionMakers(ids,{perPage:Math.min(10,perPage)});const candidates=people.people.filter(p=>p.id).slice(0,Math.min(10,Math.max(1,maxPeople)));if(!candidates.length)return {connector:"apollo_enrichment",status:"live",domain,contacts:[],meta:{requested:0,credits:"no enrichment performed"}};const data=await request("/people/bulk_match?reveal_personal_emails=false&reveal_phone_number=false",{details:candidates.map(p=>({id:p.id}))},"enrichment");const matches=(data.matches||[]).map(p=>({id:p.id||null,person:[p.first_name,p.last_name].filter(Boolean).join(" ")||p.name||"Unknown",role:p.title||null,company:p.organization?.name||p.organization_name||null,organization_id:p.organization_id||p.organization?.id||null,email:p.email||null,email_status:p.email_status||null,linkedin_url:p.linkedin_url||null,city:p.city||null,state:p.state||null,country:p.country||null,match_confidence:p.match_confidence||null,source:"Apollo People Enrichment"}));return {connector:"apollo_enrichment",status:"live",domain,contacts:matches,meta:{requested:candidates.length,enriched:matches.length,credits:"Apollo enrichment is disabled unless explicitly enabled"}};}
async function research(domain,options={}){const companies=await findCompanies(domain,options);const ids=companies.organizations.map(x=>x.id).filter(Boolean);const people=await findDecisionMakers(ids,options);return {...companies,people,evidence:companies.organizations.slice(0,10).map(org=>({type:"buyer_candidate",source:"Apollo People API Search",source_url:org.website_url||"https://www.apollo.io/",observed_at:new Date().toISOString(),confidence:"medium",supports:"company_fit_and_buyer_discovery",status:"observed",company:org.name,matched_terms:org.matched_terms}))};}
module.exports={findCompanies,findDecisionMakers,enrichDecisionMakers,research};