import fs from "node:fs";
import path from "node:path";

const root=process.cwd(), dir=path.join(root,"agent"), stateFile=path.join(dir,"state.json"), runsDir=path.join(dir,"runs");
fs.mkdirSync(runsDir,{recursive:true});
const ASSET=process.env.AGENT_ASSET||"robotembodiment.com";
const QUERY=process.env.AGENT_QUERY||"humanoid robotics embodied AI robot learning";
const GOAL=process.env.AGENT_GOAL||"Find qualified buyers for robotembodiment.com";
const ALIASES={"figure":"Figure AI","figure ai":"Figure AI","physical intelligence":"Physical Intelligence","skild ai":"Skild AI","sanctuary ai":"Sanctuary AI","nvidia":"NVIDIA","google deepmind":"Google DeepMind","toyota":"Toyota","dexterity":"Dexterity","covariant":"Covariant","robust.ai":"Robust.AI","unitree":"Unitree Robotics","limx dynamics":"LimX Dynamics","pudu robotics":"Pudu Robotics","agility robotics":"Agility Robotics","apptronik":"Apptronik","1x":"1X Technologies","neura robotics":"NEURA Robotics","spirit ai":"Spirit AI","anybotics":"ANYbotics","boston dynamics":"Boston Dynamics","agibot":"AGIBOT","ubtech":"UBTECH Robotics","tesla":"Tesla","amazon":"Amazon","meta":"Meta","microsoft":"Microsoft","waymo":"Waymo"};
const KNOWN=new Set(Object.values(ALIASES).map(x=>x.toLowerCase()));
const COMPANY_SEEDS=["Figure AI","Physical Intelligence","Skild AI","Sanctuary AI","Agility Robotics","Apptronik","1X Technologies","NEURA Robotics","Unitree Robotics","Boston Dynamics","Dexterity","Covariant","Robust.AI","NVIDIA","Google DeepMind","Pudu Robotics","ANYbotics","UBTECH Robotics","LimX Dynamics","Tesla"];
const PROJECT=/\b(portfolio|student|internship|course|tutorial|workshop|assignment|simulator|demo|personal project|textbook|book|notes|university|school|classroom)\b/i;
const NOISE=/^(physical|physical ai|embodied|embodied ai|robotics|robot|ai|artificial intelligence|machine learning|open source|github|workshop|simulator|tutorial|demo|project|research|engineering|learning|lab)$/i;
const norm=v=>String(v||"").replace(/[-_]+/g," ").replace(/\s+/g," ").trim();
const age=v=>Math.max(0,(Date.now()-new Date(v||0).getTime())/86400000);
function canonical(v){const raw=norm(v),k=raw.toLowerCase();if(ALIASES[k])return ALIASES[k];const n=raw.replace(/^the\s+/i,"");return !n||n.length<3||n.length>70||NOISE.test(n)||PROJECT.test(n)?"":n}
function type(s){const t=(s.title+" "+s.description).toLowerCase();if(/fund|raised|funding|investment|acqui|partner|partnership|launch|contract|customer|order|expansion|deployment|commercial/.test(t))return"COMMERCIAL";if(/hire|hiring|job|recruit|joins|team|vacancy/.test(t))return"HIRING";if(/robot|robotics|humanoid|embodied|manipulation|reinforcement|simulation|foundation model|behavior|planning|autonomy|physical ai|vla/.test(t))return"TECHNICAL";return"MARKET"}
function entities(s){const out=[],push=x=>{x=canonical(x);if(x&&!out.includes(x))out.push(x)};let m;const full=(s.title||"")+" "+(s.description||"");const known=/\b(Figure AI|Physical Intelligence|Skild AI|Sanctuary AI|NVIDIA|Google DeepMind|Toyota|Dexterity|Covariant|Robust\.AI|LimX Dynamics|Pudu Robotics|Agility Robotics|Apptronik|1X Technologies|NEURA Robotics|Spirit AI|ANYbotics|Boston Dynamics|AGIBOT|UBTECH Robotics|Tesla|Amazon|Meta|Microsoft|Waymo)\b/gi;while((m=known.exec(full)))push(m[1]);const pats=[/\b([A-Z][A-Za-z0-9&.\-]+(?:\s+[A-Z][A-Za-z0-9&.\-]+){0,4}),?\s+(?:Inc\.?|Corp\.?|Corporation|Company|Robotics|AI|Labs?|Dynamics|Technologies)\b/g,/\b([A-Z][A-Za-z0-9&.\-]+(?:\s+[A-Z][A-Za-z0-9&.\-]+){0,4})\s+(?:is|was|builds|develops|founded|launches|raises|partners|hires|deploys)\b/g];for(const re of pats)while((m=re.exec(full)))push(m[1]);if(s.ownerType==="Organization" && ALIASES[String(s.ownerLogin||"").toLowerCase()])push(s.ownerLogin);return out}
function qualify(name,signals){const text=(name+" "+signals.map(s=>s.title+" "+s.description).join(" ")).toLowerCase(),known=KNOWN.has(name.toLowerCase()),company=/\b(company|inc\.?|corp\.?|startup|founded|funded|funding|enterprise|product|platform|commercial|robotics company|ai company)\b/i.test(text),robotics=/robot|robotics|humanoid|embodied|physical ai|manipulation|autonomy|robot learning/i.test(text),project=PROJECT.test(text)||/\b(lab|university|school)\b/i.test(name),commercial=signals.filter(s=>type(s)==="COMMERCIAL").length,hiring=signals.filter(s=>type(s)==="HIRING").length,fresh=signals.filter(s=>age(s.publishedAt)<=90).length;let score=(known?30:0)+(company?25:0)+(robotics?15:0)+(commercial?20:0)+(hiring?12:0)+Math.min(12,fresh*4);if(project)score-=45;return{qualified:!project&&(known||company)&&robotics&&score>=55,score:Math.max(0,Math.min(100,Math.round(score))),reason:project?"Research/education/project noise.":!robotics?"Insufficient robotics relevance.":!(known||company)?"No reliable company identity.":score<55?"Commercial threshold not met.":"Company identity and robotics relevance supported.",commercial,hiring,fresh}}
async function json(url,headers={}){const r=await fetch(url,{headers});if(!r.ok)throw new Error(r.status+" "+r.statusText);return r.json()}
async function search(q){const [g,h]=await Promise.allSettled([json("https://api.github.com/search/repositories?q="+encodeURIComponent(q)+"&sort=updated&order=desc&per_page=15",{accept:"application/vnd.github+json"}),json("https://hn.algolia.com/api/v1/search?query="+encodeURIComponent(q)+"&tags=story&hitsPerPage=15")]);const out=[];if(g.status==="fulfilled")for(const x of g.value.items||[])out.push({source:"GitHub",url:x.html_url,title:x.full_name,description:x.description||"",publishedAt:x.updated_at,ownerLogin:x.owner?.login||"",ownerType:x.owner?.type||""});if(h.status==="fulfilled")for(const x of h.value.hits||[])out.push({source:"Hacker News",url:x.url||("https://news.ycombinator.com/item?id="+x.objectID),title:x.title||"",description:x.title||"",publishedAt:x.created_at});return out}
function load(){try{return JSON.parse(fs.readFileSync(stateFile,"utf8"))}catch{return{version:2,status:"IDLE",runs:[]}}}
async function main(){const startedAt=new Date().toISOString(),state=load(),terms=[QUERY,ASSET.replace(/\.[a-z0-9]+$/i,"").replace(/[._-]/g," "),QUERY+" company",QUERY+" funding",QUERY+" hiring",QUERY+" launch",QUERY+" humanoid",QUERY+" embodied AI",QUERY+" robotics company",...COMPANY_SEEDS.map(x=>x+" robotics"),...COMPANY_SEEDS.map(x=>x+" funding"),...COMPANY_SEEDS.map(x=>x+" hiring"),...COMPANY_SEEDS.map(x=>x+" launch")],raw=[];for(const q of [...new Set(terms)]){try{raw.push(...await search(q))}catch{}}const seen=new Set(),evidence=raw.filter(x=>age(x.publishedAt)<=730).filter(x=>{const k=x.source+"|"+x.url;if(seen.has(k))return false;seen.add(k);return true});const groups={};for(const s of evidence)for(const n of entities(s)){const k=n.toLowerCase();groups[k]??={name:n,signals:[]};groups[k].signals.push(s)}const candidates=[],watch=[],rejected=[];for(const g of Object.values(groups)){const q=qualify(g.name,g.signals);const trigger=g.signals.slice().sort((a,b)=>(({COMMERCIAL:5,HIRING:4,TECHNICAL:3,MARKET:1}[type(b)]||1)-({COMMERCIAL:5,HIRING:4,TECHNICAL:3,MARKET:1}[type(a)]||1))||new Date(b.publishedAt)-new Date(a.publishedAt))[0];const item={name:g.name,score:q.score,evidence:g.signals.length,commercial:q.commercial,hiring:q.hiring,recent:q.fresh,trigger,reason:q.reason};q.qualified?candidates.push(item):(!/noise|project|education/i.test(q.reason)&&q.score>=35&&(q.commercial||q.hiring||g.signals.some(s=>type(s)==="TECHNICAL"))?watch.push(item):rejected.push(item))}candidates.sort((a,b)=>b.score-a.score);watch.sort((a,b)=>b.score-a.score);const run={id:startedAt.replace(/[:.]/g,"-"),startedAt,goal:GOAL,asset:ASSET,query:QUERY,evidence,candidates,watch,rejected,metrics:{signals:evidence.length,qualified:candidates.length,watch:watch.length,rejected:rejected.length,fresh:candidates.filter(x=>age(x.trigger?.publishedAt)<=30).length},decision:candidates.length?"QUALIFIED_OPPORTUNITIES_FOUND":"NO_QUALIFIED_BUYER"};run.checkpoint=JSON.parse(JSON.stringify(state));state.version=2;state.status="DONE";state.lastRun=run.id;state.runs=[...(state.runs||[]),{id:run.id,at:startedAt,decision:run.decision,qualified:candidates.length,rejected:rejected.length}].slice(-50);fs.writeFileSync(stateFile,JSON.stringify(state,null,2)+"\n");fs.writeFileSync(path.join(runsDir,run.id+".json"),JSON.stringify(run,null,2)+"\n");console.log(JSON.stringify({decision:run.decision,metrics:run.metrics,candidates:candidates.slice(0,10)}))}
main().catch(e=>{console.error(e);process.exitCode=1});
